# Generated by Django 5.1.7 on 2025-03-18 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ascii_transforms", "0002_asciitransform_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ASCIIMatrixCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character", models.CharField(max_length=1)),
                (
                    "red",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "green",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "blue",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "ascii_transform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="ascii_transforms.asciitransform",
                    ),
                ),
            ],
        ),
    ]
