# Generated by Django 5.1.7 on 2025-03-19 11:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ascii_transforms", "0003_asciimatrixcell"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="asciitransform",
            name="character_matrix",
        ),
        migrations.CreateModel(
            name="ASCIITransformCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "column",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("character", models.CharField(max_length=1)),
                (
                    "red",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "green",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "blue",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(255),
                        ]
                    ),
                ),
                (
                    "ascii_transform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="ascii_transforms.asciitransform",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ASCIIMatrixCell",
        ),
    ]
