# Generated by Django 5.1.7 on 2025-03-19 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ascii_transforms", "0004_remove_asciitransform_character_matrix_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asciitransform",
            name="dimension",
            field=models.IntegerField(
                default=2, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
    ]
